enable.csh.in, enable.in
With these changes we can *optionally* put a file `local` (bash) or `local.csh`(csh) alongside the main enable script, which can be used to set additional local variables.
=> Added ability source a file local / local.csh

enable.in
In bash spaces around the assignment operator is invalid.
=> Fixed invalid bash assignment

bin/kmd, setup-py.sh, setup-wheel.sh
For testing.
Using `--executable $PYTHON` is wrong, `--executable $PREFIX/bin/python` is slightly better.  Should be `--executable $PATH_TO_NEW_PYTHON`.
=> Set "correct" executable in setuptools

bin/kmd
Added `sphinx` to postprocess hack.
This should at some point be fixed by getting `pip` to respect `executable` argument.
=> Add sphinx to postprocess hack

enable.csh.in
I consider it quite unrealistic that we will make any headway with the csh deprecation before the end of Q2 2018 - I therefor suggest we remove this message.
=> Remove csh deprecation warning

bin/kmd, komodo/__init__.py, tests/test_tree_cmp.py
This PR adds a config option: `--inplace-depoly` - when that is set to true the program will check that the file system structure is unchanged (i.e. the same distribution of files & directories) - if that is the case the final installation will be done in-place with:
```
rsync -ac $release /project/res/komodo
```
=> Add in-place deploy option

bin/kmd, komodo/__init__.py
I got so frustrated by comparing file-system trees ....
It will now always return `True` - but with a better error message
=> Changed tree_equal implementation + always true

komodo/lint.py, setup.py
Make the linter available as an executable from the command line when komodo is installed
=> Install linter as komodo-lint

.travis.yml, komodo/fetch.py, requirements.txt
If the main branch of a repository is broken beyond cloning Komodo will fail. With this change we clone the requested branch or tag directly. In addition, I've set `depth 1`, so this patch might also lead to slightly faster cloning time.
*Note:*
`shell` was missing from the requirements and _Komodo_ did not immediately seem to be Python 3 compabitle. Did fix version and update dependencies. Python 3 compatibility can be dealt with in another PR.
=> Clone version directly

komodo/fetch.py
Version for an application is wrong when scm_version is used and the
depth arguments is included. The last applicable tag will not be cloned
and as such the version given would be 0.0.dev+..
When looking through the issues the following popped up: https://github.com/equinor/komodo/issues/16 I believe this issue can be closed as this is the reason this PR exists (although correct behaviour was observed prior to the `depth` keyword being included, and that is much later than the issue date)
=> Remove depth from git fetch

python-mk.sh
Currently 3 tests are failing while doing make - but those are not
critical and just tests on responses when making bad requests. Our proxy
is not behaving as tests expects.
=> Remove set -e which causes build process to exit.

jenkins/link.sh
Will replace the current link job, and extend it so that you can cross link (e.g. from prog to project).
=> Add link job that can cross link

setup-py.sh
Not sure why these are present - they was used when pip installing dependencies on our packages - or at least they were present in the code. Will try to remove these and make the installation more like how normal pip packages is installed. 
Don't think this will fix the dirty version issue - but at least it's a good thing removing fluff we don't need (hopefully)
=> Remove args when pip installing git downloaded libs

jenkins/set_permissions.sh
Fixes https://github.com/equinor/scout/issues/164
After landing, `PERMISSIONS_EXEC` can be changed from `/project/res/bin/res_perm` to `../jenkins/set_permissions.sh` in all komodo build jobs.
=> Add script to set permissions on builds

komodo/build.py
Pip, if it finds an existing package, doesn't install it again even if we've specified `--root`/`--prefix`. This was discovered when we updated the version of `six` to be the same as latest. Komodo has `six` as one of its dependencies and so pip discovered that it was already installed in the temporary Komodo virtualenv, and so didn't install it into the release.
I still need to have Jenkins use Python 3 for running Komodo regardless of what the bundle python will be, but that isn't critical yet.
=> Have pip force-reinstall packages always

komodo/prettier.py, komodo/release_transpiler.py, setup.py, tests/data/test_release_matrix.yml, tests/test_release_transpiler.py
respolves #116 
The matrix builder including hardcoded builtins are to be removed after creating the initial release matrix files for bleeding and the newest release at the given time.
=> Transpiler

.travis.yml, ci/travis/build_lib.sh, ci/travis/test_import_lib.py, enable.csh.in, enable.in, komodo/cli.py, komodo/shim.py, tests/test_shim.py
Currently we are setting `LD_LIBRARY_PATH` when komodo is enabled. If it is sourced in the user's `.bashrc`, it breaks a lot of system-managed software, most notably GNOME (Our `libxkbcommon.so` that we ship with komodo causes a segfault in `gnome-shell`).
This is yet another proposal on how to fix this. Instead of changing `LD_LIBRARY_PATH` when komodo is enabled, we delay it until the user actually runs some program that we provide. Thus, `LD_LIBRARY_PATH` affects only the program the user wanted and any child processes that it may spawn.
We do this thusly:
1. Build a release as normal
2. At the end, rename `bin/` to `libexec/`
3. For each entry in `libexec/`:
1. Create a 0755 entry in `bin/` with the same name, containing the following bash script:
```bash
#!/bin/bash -eu …
```
=> Delay setting LD_LIBRARY_PATH until executing something from bin/

komodo/shim.py
`komodo_job_dispatch` is a script called by ERT's job queue, which unsets the komodo environment before sourcing it again. Among these things, `LD_LIBRARY_PATH` is removed. However, it doesn't remove `_KOMODO_SHIM`, so the next time a shimmed executable is started, `LD_LIBRARY_PATH` isn't set again.
=> Don't set _KOMODO_SHIM

komodo/shim.py
Some of our machines have broken `/etc/bash` that checks whether PS1 is set via `${PS1}` instead of `${PS1:-}`.
=> Don't use #!/bin/bash -eu

komodo/reverse_dep_graph.py, tests/test_reverse_dep_graph.py
Can print a textual hierachical ascii thingy, or a dot graph description. Can also call "dot" and "display" to visualise the graph.
Example:
`python komodo/reverse_dep_graph.py releases/bleeding-py36.yml repository.yml --display_dot`
=> add reverse dependency graph extractor

komodo/cli.py
In order to use newer pip version, enusre that the same tmp folder is used throughout, otherwise pip apparently gets confused.
=> Set tmp folder

komodo/__init__.py, komodo/lint.py, tests/test_lint.py
Resolves: #95 
Add linting that will check if a release name ends with one of: `-py27`, `-py36`, `-py27-rhel6`, `-py27-rhel7`, `-py36-rhel6`, `-py36-rhel7`.
=> Lint release file names

komodo/data/setup-py.sh
DESTDIR is used by Komodo and other build packagers to compile the software when there is no access `/usr`. When installing Python packages, this is entirely superfluous, and actually breaks skbuild's build process, which gets incorrectly prefixed with the value of DESTDIR.
=> Unset DESTDIR when pip install .

komodo/__init__.py, komodo/build.py, komodo/cli.py, komodo/fetch.py, komodo/lint_package_status.py, komodo/package_version.py, komodo/release_cleanup.py, komodo/release_transpiler.py, komodo/shebang.py, komodo/yaml_file_type.py, tests/test_build.py, tests/test_enable_scipts.py, tests/test_fetch.py, tests/test_komodo.py, tests/test_prettier.py
Implement the repository field "pypi_package_name" to specify name of a package in pypi when installing via `pip_install`.
=> Add package_name field to pip_install

komodo/data/build__ncdu.sh
Get the following error when building `ncdu`:
```
Installing ncdu (v1.15.1) from sh
[/tmp/jenkins-komodo-f_komodo/workspace/x-build-some-other/2021.01.rc0-py36-rhel7/komodo-releases/cache/ncdu-1.15.1]> bash /tmp/jenkins-komodo-f_komodo/workspace/x-build-some-other/2021.01.rc0-py36-rhel7/komodo/boot/kmd-env/lib64/python3.6/site-packages/komodo/data/build__ncdu.sh --prefix /prog/res/komodo/2021.01.rc0-py36-rhel7/root --fakeroot /tmp/jenkins-komodo-f_komodo/workspace/x-build-some-other/2021.01.rc0-py36-rhel7/komodo-releases/2021.01.rc0-py36-rhel7 --python /prog/res/komodo/2021.01.rc0-py36-rhel7/root/bin/python --jobs 6 --cmake cmake --pythonpath /tmp/jenkins-komodo-f_komodo/workspace/x-build-some-other/2021.01.rc0-py36-rhel7/komodo-releases/2021.01.rc0-py36-rhel7/prog/res/komodo/2021.01.rc0-p …
```
=> Disable dependency tracking when building ncdu

komodo/data/activator_switch.csh.tmpl, tests/test_switch.py
Using $prompt here causes the komodo release version to double up in the user's
PS1. The bash version of this uses $_PRE_KOMODO_PS1 and so should the csh
version.
Resolves: #181
=> csh: Use $_PRE_KOMODO_PS1 instead of $prompt

komodo/data/activator_switch.csh.tmpl, tests/test_switch.py
The enable.csh file defines `$_KOMODO_OLD_PROMPT` rather than `$_PRE_KOMODO_PS1` for whatever reason. :sweat: 
https://github.com/equinor/komodo/blob/a84813ee904a24cb9ed93275671f2cb6c320c13a/komodo/data/enable.csh.in#L51
=> csh: It's called $_KOMODO_OLD_PROMPT

vars/testKomodo.groovy
After `komodoenv` v0.3 has a `--no-update` option for releases that are not
meant to be updated, ie. singular releases.
As the komodo integration tests are usually run on non-symlinked (before a
`unstable` symlink is created), `komodoenv` started failing. Adding
`--no-update` fixes this.
=> Add --no-update to komodoenv command

vars/xUnitTest.groovy
Since we now have more worker-nodes we can afford to run xunittest on more nodes
=> Remove agent requirements for xUnitTest

komodo/data/enable.csh.in, komodo/data/enable.in
komodo version are logged also when using ERT, thus logging when sourcing does not provide much value.
=> Remove logging of komodo usage

vars/testKomodo.groovy
Newer version of matplotlib is failing at `import matplotlib.pyplot` when running in a headless environment as it tries to set backend to qtagg which requires an interactive environment. The backend can be set by using the env variable MPLBACKEND, and should be headless for all tests running on jenkins. Thus setting it in the testKomodo script.
=> Set mpl backend to headless agg

setup.py
Importlib_metadata needs to be recent due to conflicts with upstream pysnyk libraly. Therefore creating our own at the moment until the issue https://github.com/snyk-labs/pysnyk/issues is resolved
=> Update pysnyk to equinor version enabling latest importlib_metadata

.github/workflows/test.yml, bootstrap.sh, setup.py
Komodo (the tool) will require Python 3.8. The Python version in the
output Komodo environment is unaffected by this change.
=> Drop Python 3.6 support for the tool

jenkins/symlink/suggester/Jenkinsfile
Symlink suggester fails due to pysnyk requires `>=Python3.7` hence sourcing Python3.8 first.
=> Source python3.8 in symlink suggester

setup.py
Tried to install `komodo` locally on Python 3.6, but that failed due to the given dependency version constraints are not available on Python 3.6.
Added `python_requires` in order to communicate minimum Python version (which is 3.8 after #245).
=> Add `python_requires` to `setup.py`

vars/komodo.groovy, vars/testKomodo.groovy, vars/xUnitTest.groovy
Run all komodo integration tests for different repositories against 3.8 instead of 3.6 by default.
=> Run all komodo integration tests against bleeding-py38

vars/komodo.groovy
Standard RH7 swig is ancient (2.0.10). A newer swig exists and komodo
should offer to set it, granted that CMP0074[1] has been set to NEW.
[1] https://cmake.org/cmake/help/latest/policy/CMP0074.html
=> Provide newer swig via SWIG_ROOT environment var

README.md, jenkins/matrix-build/Jenkinsfile, komodo/lint.py, komodo/matrix.py, tests/test_matrix.py, tests/test_non_deployed.py, tests/test_release_cleanup.py, tests/test_release_transpiler.py
Remove Python 3.6 from default build matrix
=> Remove Python 3.6 from default build matrix

komodo/lint.py
We don't need to see this warning, as the code itself catches the same situation
=> Mute PkgResourcesDeprecationWarning

vars/testKomodo.groovy
This reverts commit c249158ca1941c6d98eee638216bf5eca1e21a7a.
Still used by ecl.
=> Revert "Remove unused equinor testdata root"

.github/workflows/test.yml, vars/xUnitTest.groovy
To prevent deadlocks with only orchestrating jobs, we reduce the nodes these jobs can run on.
=> Change nodes for xUnitTest to run on label 'orchestrating'

.github/workflows/style.yml, .github/workflows/test.yml
v2 gives a deprecation warning
=> Bump github actions/checkout to v3

komodo/build.py, komodo/cli.py, komodo/fetch.py
Improves the user interface with new group of 'required named arguments'.
Required overriding the 'optional arguments' group as well to get --help
to continue to make sense.
Also adds a more sensible default value for kmd's --cache (for pip); the
previous default of `.` caused the application to crash.
Not totally sure how this will merge with Håvard's recent PR.
=> Group kmd arguments and provide better cache default

README.md
The README example was out of date and did not work. This change includes a minimal working example, and also moves things around a bit to make it easier for a new user to approach.
Fixes #257
See #280
=> Improve README with working example

komodo/deployed.py, tests/test_non_deployed.py
This makes it possible to skip an extra jq step in Github actions
=> Avoid whitespace in json output

komodo/fetch.py, tests/test_fetch.py, tests/test_lint.py
Any jinja2 template found in the source part for packages in repository.yml will be expanded for environment variables.
=> Add support for obtaining github tokens from env

README.md, komodo/show_version.py, komodo/yaml_file_type.py, setup.py, tests/conftest.py, tests/test_show_version.py
The commit contains a new CLI tool, komodo-show-version (named after pip show, which shows more than just version). It detects the active environment and looks up the version (or git commit hash for non-pip packages) from the 'manifest', a text file komodo creates at build time. Works for komodo and komodoenv environments.
The commit also contains tests.
fixes #278
=> add cli tool to query version of package in build

komodo/check_up_to_date_pypi.py, komodo/cli.py, komodo/extract_dep_graph.py, komodo/fetch.py, komodo/insert_proposals.py, komodo/lint.py, komodo/lint_maturity.py, komodo/lint_package_status.py, komodo/maintainer.py, komodo/post_messages.py, komodo/release_cleanup.py, komodo/release_transpiler.py, komodo/reverse_dep_graph.py, komodo/show_version.py, komodo/snyk_reporting.py
Most of the CLI tools in Komodo had help strings, but the main one, `kmd`, was missing most of them. This commit makes them all more consistent with each other, and fills in some gaps.
resolves #288
[edit: preformatted text omitted by git CLI]
=> add help strings for all CLIs

komodo/show_version.py
Letting main() return a string will have it printed to stderr
=> Let komodo-show-version print to stdout

ci/test_import_lib.py, dev-requirements.txt, komodo/matrix.py, komodo/prettier.py, komodo/release_transpiler.py, tests/data/test_release_matrix.yml, tests/test_matrix.py, tests/test_release_transpiler.py
=> Add arguments to transpile

komodo/switch.py
The current message looks outdate, since reel6 was already phased out.
Probably could have removed it completely, but better to fail more gracefully if the user falls in the exception.
```
cat /lustre1/prog/komodo/2023.03.01-py38/enable
if [[ $(uname -r) == *el7* ]] ; then
export KOMODO_ROOT=/lustre1/prog/komodo
KOMODO_RELEASE_REAL=2023.03.01-py38
source $KOMODO_ROOT/$KOMODO_RELEASE_REAL-rhel7/enable
export PS1="(${KOMODO_RELEASE_REAL}) ${_PRE_KOMODO_PS1}"
export KOMODO_RELEASE=$KOMODO_RELEASE_REAL
else
echo -e "Attention! Your machine is running on a RHEL6 environment which is in the process of being phased out.
New versions of komodo will from October 2020 only support RHEL7.
Please migrate as soon as possible. If you have any questions or issues - contact us on #ert-users on Slack or …
```
=> Update migration warning

ci/func_def.sh
This is based on code staring and trying to deduce why we have the failure in 
https://github.com/equinor/komodo-releases/actions/runs/5183563004/jobs/9341978584
```
Submitting: ../mock_bsub -o /mnt/scratch/f_scout_ci/actions-runner-05/_temp/pytest_tmp_dir/pytest-of-f_scout_ci/pytest-0/test_run_mocked_lsf_queue_fail0/test_data/poly_out/realization-7/iter-0/poly_7.LSF-stdout -J poly_7 -n 1 /mnt/scratch/f_scout_ci/actions-runner-05/_temp/test-kenv/root/shims/job_dispatch.py /mnt/scratch/f_scout_ci/actions-runner-05/_temp/pytest_tmp_dir/pytest-of-f_scout_ci/pytest-0/test_run_mocked_lsf_queue_fail0/test_data/poly_out/realization-7/iter-0
1151
+ popd
1152
+ [[ ert == \e\r\t ]]
1153
+ bash ci/run_ert_ctests.sh build_and_test
1154
/mnt/scratch/f_scout_ci/actions-runner-05/_temp/test_root …
```
=> Add missing popd

komodo/symlink/create_links.py, tests/test_link_io_structure.py
This allows for forwarding of what the symlink creator actually did to status dashboards.
=> Make creating symlinks verbose

komodo/release_transpiler.py, tests/data/test_repository.yml, tests/test_release_cleanup.py, tests/test_release_transpiler.py
this adds a transpiler that can create a pip requirements file from a release matrix file (and a repo).
could for instance be used in workflows as input for checking dependency conflicts, checking for upgradable packages, or scanning for vulnerabilities.
=> Add transpiler to produce pip requirements file

komodo/lint_upgrade_proposals.py, tests/test_lint_upgrade_proposals.py
Changed return type on valid linting from SystemExit to print, as this would break the workflow where the linter is run.
=> Fix komodo-lint-upgrade-proposals return type

komodo/lint_maturity.py
This ensure that the context is preserved when we issue warnings using function wrappers.
Solves flake B028, which for some reason does not seem to trigger on Python 3.10, but does so locally on Python 3.8
=> Be explicit about stacklevel

komodo/yaml_file_types.py, tests/test_yaml_file_types.py
This fixes two bugs:
* komodo-transpiler writes yaml files with yml-suffix, while this function assumed it was yaml as suffix.
* ReleaseFile()(yaml_file) did not give a generator that  can use, changed to use content and put it in a subdictionary.
=> Fix ReleaseDir class to load *yml files

pyproject.toml
Due to RHEL7 is incompatible with urllib>2 we need to pin it
=> Pin urllib3 < 2

komodo/check_up_to_date_pypi.py, tests/test_up_to_date_pypi.py
Resolves #342
Resolves #414 
Depends on #386
=> Add flag for ignoring entries check pypi script

komodo/lint_maturity.py, tests/test_lint_maturity.py
The komodo lint maturity script fails when testing locally because it is not removing the file extension before checking if the release name is valid. The commit also updates the outdated tests.
=> Fix komodo lint maturity not ignoring file extension

komodo/cli.py, komodo/shell.py
The rm <build>.delete statement has been observed to be flaky on NFS filesystems, probably due to leftover .nfs* files blocking deletion of the directories.
We fix this by moving the old release to a unique filename, and let the rm command fail (will be logged to stdout). Subsequent builds will do the cleanup.
=> Allow a rm command to fail

komodo/lint_upgrade_proposals.py, tests/test_lint_upgrade_proposals.py
The new upgrade-proposals linter threw an error if there were multiple releases being upgraded at the same time. This is an intended feature, so that is being removed from the linter in this commit.
=> Fix upgrade-proposals linter bug for multiple releases

.github/workflows/docs.yml, .github/workflows/style.yml, .github/workflows/test.yml, CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, SECURITY.md
Resolves https://github.com/equinor/scout/issues/966
=> Julevask 2023

komodo/cli.py, tests/test_cli.py
Only bleeding builds will be overwritten by default.
Solves the komodo part of https://github.com/equinor/komodo-releases/issues/5063
=> Add guard to avoid overwriting releases

komodo/snyk_reporting.py, tests/test_snyk_reporting.py
This PR fixes the issue where the script reports vulnerabilities in versions not used in the release. An example of this was numpy 1.21.3 vulnerabilities being reported, even though we do not use numpy 1.21.3. The reason this was reported was that it is dependency in patsy, but it is never mentioned that it is an indirect dependency. This PR makes it so that the script filters out vulnerable versions that are not present in the release.
=> Fix komodo-snyk-test reporting odd package versions

komodo/symlink/sanity_check.py, tests/test_link_io_structure.py
This makes the printed diff from the sanity checker make sense
Solves #481
=> Handle non-sorted lists in dicts when comparing dicts

komodo/lint_upgrade_proposals.py, tests/test_lint_upgrade_proposals.py
```
2024-02:
2024-03:
2024-04:
cwrap: 1.6.6
everest: 0.33.4
seba:
py38: 7.5.0
py311: 7.5.0
dask:
rhel7:
py38: 2023.5.0
rhel8:
py38: 2023.5.0
py311: 2024.4.0
py38: 2024.4.0
```
Yields:
```
Found package: 'cwrap' with version 1.6.6 in repository
Found package: 'everest' with version 0.33.4 in repository
Found package: 'seba' with version 7.5.0 in repository
Found package: 'seba' with version 7.5.0 in repository
Found package: 'dask' with version 2023.5.0 in repository
Found package: 'dask' with version 2023.5.0 in repository
Found package: 'dask' with version 2024.4.0 in repository
Found package: 'dask' with version 2024.4.0 in repository
Found upgrades
Upgrade proposals file is valid!
```
=> Allow CommentedMap when linting upgrade proposals

komodo/lint.py, komodo/pypi_dependencies.py
Issue:
Only requirements are printed when komodo linting fails.
ref.
https://github.com/equinor/komodo-releases/actions/runs/10826893274/job/30038841723?pr=6267
Prints package name alongside requirements:
```
(rhel8-bleed-py38-env + bleeding-py38-rhel8) [andrli@st-lintgxt0002 komodo-releases]$ komodo-lint --check-pypi-dependencies releases/2024.10.b0-py38-rhel8.yml repository.yml
303 packages
Failed requirements
fmu-dataio
pydantic<2.7.0,>=2.5.0
Error in komodo configuration.
```
Also, introducing an older version of `Semeio` cause this to happen;
```
(rhel8-env + 2024.09.02-py38-rhel8) [andrli@st-lintgx0138 komodo-releases]$ komodo-lint --check-pypi-dependencies releases/2024.10.b0-py38-rhel8.yml repository.yml
Not installed: ecl
Not installed: configsuite
Not installed: stea
303 …
```
=> Add package name to error messages

komodo/symlink/sanity_check.py, pyproject.toml, tests/test_link_io_structure.py
Resolves #512 
We have altered how symlinks are being interpreted when introducing multiple rhel-versions, and when introducing bleeding-timestamped builds.
The concept of root-link does not fully match here, where we source symlinks based on OS versions in enable scripts, and therefore have no clean linkage as we used to have.
=> Avoid certain symlinks when checking for consistencies

komodo/symlink/sanity_check.py
Resolves equinor/komodo-releases#6529
bleeding-<py_version> is now a symlink pointing to the latest bleeding-<timestamp>-<py_version> 
This symlink is autogenerated during the build workflow to get the correct timestamp and is therefore 
not part of the symlink configuration file
=> Avoid bleeding pyversion symlinks when checking for inconsistencies

komodo/symlink/sanity_check.py, komodo/symlink/suggester/cli.py, komodo/symlink/suggester/configuration.py, tests/test_sanity_check.py, tests/test_suggester.py
Resolves https://github.com/equinor/komodo-releases/issues/6405
When using the propose symlink pr workflow, this yielded the following:
Symlink change `deprecated` to `2024.11.12`
```diff
diff --git a/symlink_configuration/symlink_config.json b/symlink_configuration/symlink_config.json
index 7bfc3b20..03c9fe5d 100644
--- a/symlink_configuration/symlink_config.json
+++ b/symlink_configuration/symlink_config.json
@@ -54,2 +54,2 @@
-        "2024.11-py311": "2024.11.11-py311",
-        "2024.11-py38": "2024.11.11-py38",
+        "2024.11-py311": "2024.11.12-py311",
+        "2024.11-py38": "2024.11.12-py38",
@@ -64 +64 @@
-        "deprecated-py311": "2024.10-py311",
+        "deprecated-py311": "2024.11-py311",
@@ -66 +66 @@
-        "deprecated-py38": "2024.10-py38",
+ …
```
=> Adds suggest deprecated symlink capability

.github/workflows/docs.yml, .github/workflows/test.yml, .gitignore, ci/release-matrix.yml, ci/repository.yml, komodo/build.py, komodo/check_unused_package.py, komodo/check_up_to_date_pypi.py, komodo/cleanup.py, komodo/cli.py, komodo/deployed.py, komodo/insert_proposals.py, komodo/lint_maturity.py, komodo/lint_symlink_config.py, komodo/maintainer.py, komodo/matrix.py, komodo/pypi_dependencies.py, komodo/release_transpiler.py, komodo/show_version.py, komodo/snyk_reporting.py, komodo/switch.py, komodo/symlink/create_links.py, komodo/symlink/suggester/cli.py, komodo/symlink/suggester/configuration.py, komodo/yaml_file_types.py, pyproject.toml, tests/test_cleanup.py, tests/test_lint_maturity.py, tests/test_release_transpiler_argument_types.py, tests/test_snyk_reporting.py
Reverts the commit that removed python 3.8 support, since it is still needed for the December release
=> Reintroduce py38 support

komodo/insert_proposals.py, komodo/release_transpiler.py, tests/test_release_transpiler.py
Adds `--auto-custom-coordinates`  flag to `komodo-transpiler`
This will find any key values in the release files other than `rhel` and `^py` tags.
Also updates `build_rhel8` -> `build_rhel9` since we are closing ground to build for that OS too.
=> Add deduction of matrix coordinates

komodo/cli.py, komodo/shell.py
=> Factor out a function to define the pip shell command

komodo/cli.py, tests/test_cli.py
komodo-shims thus becomes a magic package name that if found, will always be the last pip-package to be installed. This allows such a package to overwrite endpoints that are also installed by other packages.
=> Add feature to install komodo-shims at the end

tests/test_release_transpiler_argument_types.py
This will make it possible to run test_release_cleanup.py after running test_release_transpiler_argument_types.py
=> Avoid tainting source code repo when running tests

komodo/cli.py, tests/test_cli.py
The previous approach would only possibly work if komodo-shims was a pypi package. It will not be. With this commit, it is installed in a separate and new section, and is installed directly from its downloaded source location.
=> Move installation of komodo-shims to the end

.github/workflows/style.yml, komodo/build.py, komodo/lint.py, komodo/lint_upgrade_proposals.py, komodo/matrix.py, komodo/pypi_dependencies.py, pyproject.toml, tests/test_up_to_date_pypi.py
Not all exceptions that was needed for pylint is needed for ruff,
meaning they are not identical in their linting, but ruff is so much
faster we will let it decide.
=> Replace pylint usage with ruff

komodo/build.py
The potentially aliased package name is only relevant for pip installs fetching from pypi, but this is no longer performed in this function, rendering the overwriting of the loop variable pointless.
=> Remove pointless overwriting of package_name
