bin/kmd, enable.csh.in, enable.in, enable.m4
Just a suggetsion - will support the komodo release as an environment variable.
=> Export komodo release

komodo/shell.py
=> Print cwd in shell prompt

komodo/build.py
Hack to be able to depend on opm-common
=> Pass ddest prefix

bin/kmd, komodo/build.py, komodo/cleanup.py, komodo/fetch.py, komodo/lint.py, komodo/maintainer.py
Change yml loading. yml.load is deprecated.
=> Change 'yml.load(..)' to 'yml.safe_load(..)'

bin/kmd, komodo/__init__.py, komodo/build.py, komodo/fetch.py, python-mk.sh, setup-py.sh
depends on https://github.com/equinor/komodo-releases/pull/13
we need to merge new release / repository files in first - otherwise our builds will break
=> Make python3 compatible

jenkins/build-release.sh
Pull the script from the `komodo-advanced` job.
Will require new job variables:
```
PERMISSIONS_EXEC
ORACLE_HOME
GIT_EXEC
PROXY
PIP_CERT
DEVTOOLSET
CMAKE_EXECUTABLE
```
=> Add build-release script

README.md, komodo/__init__.py, komodo/prettier.py, requirements.txt, setup.py, tests/input/duplicate_repository.yml, tests/input/inconsistent_config.yml, tests/input/pretty_release.yml, tests/input/pretty_repository.yml, tests/input/ugly_release.yml, tests/input/ugly_repository.yml, tests/test_prettier.py
=> Added auto-style-formatter + validator

komodo/symlink/create_links.py, komodo/symlink/sanity_check.py, setup.py, tests/data/links.json, tests/data/links_full.json, tests/test_link_io_structure.py
Resolves https://github.com/equinor/scout/issues/110
=> Initial linking tool

setup.py
This dep was missing from `setup.py`.
=> Add dependency on ruamel.yaml

.travis.yml, requirements.txt
=> Remove requirements.txt

enable.csh.in, enable.in
=> Add disable_komodo command to unsource komodo

komodo/lint_package_status.py, setup.py, tests/test_lint_package_status.py
Needed for https://github.com/equinor/scout/issues/136
=> Add linting of package status files

komodo/lint_maturity.py, setup.py, tests/test_lint_maturity.py
#107 
test_lint_maturity.py under construction
=> Compare release and tag maturity

enable.in
=> Fix unbound variables in enable.sh

vars/testKomodo.groovy, vars/xUnitTest.groovy
=> Add new testing Jenkins pipeline libraries

.travis.yml, komodo/data/enable.csh.in, komodo/data/enable.in, tests/test_enable_scipts.py
=> Preserve environment from before sourcing enable

vars/testKomodo.groovy
Add environment variable for directory used for internal test data.
=> Add equinor testdata root

komodo/build.py, komodo/cli.py, komodo/fetch.py, komodo/package_version.py, tests/test_build.py, tests/test_fetch.py, tests/test_package_version.py
=> Allow for installation of LATEST_PACKAGE_ALIAS (*)

.gitignore, komodo/snyk_reporting.py, komodo/yaml_file_type.py, setup.py, tests/test_snyk_reporting.py
Add security checking for komodo releases using Snyk.
=> Add vulnerability checking with Snyk

setup.py
Install the revsere-dep-graph as an executable
=> Rev script

komodo/data/enable.csh.in, komodo/data/enable.in
=> Unset KOMODO_ROOT

vars/xUnitTest.groovy
Changing any to master||scout_ci for xUnitTest
=> Matrix on any

komodo/build.py, setup.py, tests/data/cli/nominal_release.yml, tests/data/cli/nominal_repository.yml, tests/test_cli.py
...e.g. from GitHub artifacts created by GitHub workflows on GitHub releases.
=> Support download of binary artifacts

jenkins/symlink/suggester/Jenkinsfile
=> Remove unwanted Python2 sourcing

komodo/symlink/create_links.py
Also ensure f-formatting is used
=> Remove erroneous comma in error message

komodo/cli.py
Currently only in `cli.py`. 
* Using f-strings
* Using `pathlib` instead of `os.path`.
=> Modernize cli.py

komodo/deployed.py, tests/test_non_deployed.py
This eases integration with Github actions
Resolves #301
=> Add json output option to komodo-non-deployed

.github/workflows/test.yml, komodo/cli.py, tests/test_cli.py
=> Remove usage of renamer, use plain mv instead

README.md, komodo/cli.py, tests/data/cli/minimal_release.yml, tests/data/cli/minimal_repository.yml, tests/test_cli.py
=> remove locations-config from required args

komodo/cli.py, tests/test_cli.py
Deprecated and testing but the warning is not enough to interrupt what the user sees when running the CLI. So I need to add something else.
Resolves #322
=> Deprecate pyver option in CLI

komodo/cli.py, komodo/shebang.py
=> Ignore only UnicodeDecodeError in shebang-fixing

komodo/prettier.py, komodo/release_cleanup.py, tests/test_prettier.py, tests/test_release_cleanup.py
=> Make komodo-clean-repository able to reformat again

komodo/check_up_to_date_pypi.py
As far as I understand, we pull all builds of a package from pypi, and then try to parse their version and python requirement. Some packages seem to have unparsable pre-release versions (absl-py: `1.3.0.dev-r634`), or invalid python specifiers (pyzmq: `!=3.0*`).
We ignore all types of such errors, presuming that they occur on builds that are irrelevant for us.
=> Ignore invalid versions/specifiers in pypi checker

.github/workflows/test.yml, bootstrap.sh, komodo/symlink/suggester/cli.py, tests/test_suggester.py
This hopefully makes the creation of (azure) branch more stable.
=> Make suggester branches more unique

komodo/cli.py, komodo/matrix.py, komodo/release_transpiler.py, tests/test_release_transpiler_argument_types.py
=> Add input validation to transpiler and combine

komodo/symlink/suggester/cli.py, tests/test_suggester.py
Added reference to which platform the symlink will be updated for in both the PR title and body.
Resolves [#3869](https://github.com/equinor/komodo-releases/issues/3869)
=> Add platform in symlink proposal PR

komodo/symlink/suggester/cli.py
Added a missing colon in PR template.
=> Fix typo in symlink suggester PR body

.github/workflows/test.yml, komodo/release_transpiler.py, tests/data/test_repository.yml, tests/test_cli.py, tests/test_up_to_date_pypi.py
=> Add missing pipe causing tests not be run

komodo/symlink/create_links.py, tests/test_link_io_structure.py
Resolves #392 
Depends on #391
=> Symlink create links should tell when stable implicitly moved

komodo/snyk_reporting.py
The subsequent API needs a dictionary object, not a RepositoryFile
object.
=> Fix repo dict

komodo/check_up_to_date_pypi.py, tests/test_up_to_date_pypi.py
Resolves #365 
Should not depend on but,
Depends on #388
=> Group upgrades komodo check pypi

tests/test_switch.py
=> Utilize pathlib in test_switch.py

komodo/symlink/sanity_check.py, tests/test_sanity_check.py
=> Improve error message on missing root links

komodo/data/build__pyside-dev.sh
=> Remove statoil proxy from build pyside-dev script

tests/conftest.py, tests/test_build.py, tests/test_fetch.py
=> Refactor test fixtures into conftest.py

komodo/cli.py
Resolves #433
Resolves https://github.com/equinor/komodo-releases/issues/4983
=> Use globbing prior to issuing rm command

komodo/cli.py, tests/test_cli.py
Resolves #433 
Tested globbing onprem;
```
Release glob ['/prog/res/komodo/bleeding-py38-rhel7.delete-8430752f-6d40-4961-95ee-9992bdb33890', '/prog/res/komodo/bleeding-py38-rhel7.delete-68b371ca-5665-45cb-9895-adec4af066ce', '/prog/res/komodo/bleeding-py38-rhel7.delete-29e3bdc2-4cd0-43b7-908b-8c14434eb163', '/prog/res/komodo/bleeding-py38-rhel7.delete-d499f098-5af4-4744-ac9a-ce5291ec6372', '/prog/res/komodo/bleeding-py38-rhel7.delete-fa43ca55-a05b-4aa8-8f48-f06f8fcd1ece', '/prog/res/komodo/bleeding-py38-rhel7.delete-2985440f-f11a-40e8-8fd4-4da7b6a68ce3', '/prog/res/komodo/bleeding-py38-rhel7.delete-120b4f6f-1751-4d9a-8fcf-292f672839f4', '/prog/res/komodo/bleeding-py38-rhel7.delete-02290018-9d7a-441b-9aa1-88609e85f08c', '/prog/res/komodo/bleeding-py38-rhel7.delete-b6b3dd10-09bd-4561-bfbe-53 …
```
=> Fix folder glob require f-string

komodo/check_up_to_date_pypi.py, tests/test_cli.py, tests/test_up_to_date_pypi.py
=> Improve check-pypi script

komodo/lint_maturity.py, tests/test_lint_maturity.py
This reverts commit 094e2a3350ccd947e419861eb9c69439845902a3.
=> Revert "Run lint maturity on the transpiled release file"

komodo/build.py, komodo/fetch.py, komodo/yaml_file_types.py
=> Remove RPM support

komodo/cli.py
=> Refactor CLI

komodo/insert_proposals.py, komodo/yaml_file_types.py, tests/test_insert_proposals.py
=> Refactor komodo insert proposals

komodo/cli.py, komodo/release_transpiler.py, komodo/symlink/suggester/cli.py, komodo/symlink/suggester/configuration.py, tests/data/links.json, tests/data/links_full.json, tests/test_link_io_structure.py, tests/test_sanity_check.py, tests/test_suggester.py
Resolves https://github.com/equinor/komodo-releases/issues/5878
=> Removed unstable symlink capability

komodo/symlink/suggester/cli.py, komodo/symlink/suggester/configuration.py, komodo/symlink/suggester/release.py, tests/test_suggester.py
Resolves [#4410](https://github.com/equinor/komodo-releases/issues/4410)
=> Perform changes in multiple files in one PR

komodo/data/activator_switch.csh.tmpl, komodo/data/activator_switch.tmpl, komodo/switch.py, tests/test_switch.py
Resolves equinor/komodo-releases#6493
=> Warn user if sourcing other tags than deprecated-rhel7 on RHEL7

komodo/data/activator_switch.csh.tmpl, komodo/switch.py, tests/test_switch.py
Resolves equinor/komodo-releases#6493
=> Fix multiline migration warning for csh

komodo/check_unused_package.py, tests/test_check_unused_package.py
=> Make check_unused_package raise on unknown packages

komodo/komodo_error.py, komodo/lint.py, komodo/yaml_file_types.py, tests/test_lint.py, tests/test_yaml_file_types.py
Just remove duplication and fix some type hints.
=> Refactor usage of KomodoError

komodo/check_unused_package.py, komodo/pypi_dependencies.py, tests/test_check_unused_package.py, tests/test_pypi_dependencies.py
In order to specify extras in check_unused we need to be able to set the extras field of satisfied for _check_unused . https://github.com/equinor/komodo/issues/518
=> Make it possible to specify requirements in check_unused

komodo/check_unused_package.py, komodo/pypi_dependencies.py, tests/_mock_get_pypi_requirements.py, tests/test_check_unused_package.py, tests/test_pypi_dependencies.py
resolves https://github.com/equinor/komodo/issues/518
=> Make it possible to specify extras in package_status
